"""
logger.py

Handles logging of chat interactions to the app_logs.chat_logs table in PostgreSQL.
Uses SQLAlchemy for database access. Designed for modular use across the application.

Author: Data_Insights Team
"""

from sqlalchemy import create_engine, text
from sqlalchemy.exc import SQLAlchemyError
from typing import Optional, Dict, Any
from datetime import datetime
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..')))
import config  # Centralized config access

# Utility: Get database URL from config
DATABASE_URL = config.DATABASE_URL  # Should be set in .env and config.py

# Create SQLAlchemy engine (singleton)
engine = create_engine(DATABASE_URL)

def log_chat_interaction(
    user_prompt: str,
    llm_response: str,
    llm_generated_code: Optional[str],
    response_type: str,
    page: str,
    tab: str,
    prompt_structure: Optional[Dict[str, Any]],
    session_id: Optional[str]
) -> None:
    """
    Log a chat interaction to the app_logs.chat_logs table.

    Args:
        user_prompt: The user's prompt.
        llm_response: The LLM's answer.
        llm_generated_code: Python code generated by LLM, if any.
        response_type: 'qa', 'code', 'visualization', etc.
        page: Page where chat occurred.
        tab: Tab where chat occurred.
        prompt_structure: Structured prompt context (as dict), if used.
        session_id: User/session identifier, if available.
    """
    insert_sql = text('''
        INSERT INTO app_logs.chat_logs (
            user_query, llm_response, llm_generated_code, response_type,
            page, tab, prompt_structure, session_id, created_at
        ) VALUES (
            :user_prompt, :llm_response, :llm_generated_code, :response_type,
            :page, :tab, :prompt_structure, :session_id, :created_at
        )
    ''')
    try:
        with engine.begin() as conn:
            conn.execute(insert_sql, {
                "user_prompt": user_prompt,
                "llm_response": llm_response,
                "llm_generated_code": llm_generated_code,
                "response_type": response_type,
                "page": page,
                "tab": tab,
                "prompt_structure": prompt_structure,
                "session_id": session_id,
                "created_at": datetime.utcnow()
            })
    except SQLAlchemyError as e:
        # Reason: Log errors to console for now; production apps may log to file or monitoring system
        print(f"[Logger] Failed to log chat interaction: {e}")

# Reason: This logger is modular, uses config for DB connection, and is ready for future extension.
