[browser]
    gatherUsageStats = false

[theme]
    base="dark"
    primaryColor="#00C3FF"
    backgroundColor="#010A14"
    secondaryBackgroundColor="#051B30"
    textColor="#FFFFFF"
    font="sans-serif"